export enum EmployeeCheckType {
  GENERAL_KNOWLEDGE = 'GENERAL_KNOWLEDGE',
  SAFETY_TECHNIQUE = 'SAFETY_TECHNIQUE',
  SPECIAL_WORK_PERMIT = 'SPECIAL_WORK_PERMIT',
  RESUSCITATION_TRAINING = 'RESUSCITATION_TRAINING',
  MEDICAL_EXAM = 'MEDICAL_EXAM',
}

