export enum ExamSessionStatus {
  WAITING_MODERATOR = 'WAITING_MODERATOR',
  CODE_PENDING = 'CODE_PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  AWAITING_ORAL = 'AWAITING_ORAL',
  SCHEDULING_NEXT = 'SCHEDULING_NEXT',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
